version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: property_listings_db
    environment:
      POSTGRES_DB: property_listings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: property_listings_redis
    ports:
      - "6379:6379"
    networks:
      - app_network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge