# Generated by Django 4.2.x

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property title/name', max_length=200)),
                ('description', models.TextField(help_text='Detailed property description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Property price in currency', max_digits=10)),
                ('location', models.CharField(help_text='Property location/address', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]